blank_issues_enabled: false
contact_links:
  - name: â“ Ask a Question
    url:
    about: Ask and answer al-folio related questions.
  - name: ğŸ“– Read the documentation
    url: https://EhsnAbdllh.github.io
    about: Please consult the documentation before opening any issues!
